services:
  postgres_db:
    image: pgvector/pgvector:pg17
    container_name: postgres-vector-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - vector-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  vector-data:
